
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class JavaToXmlExporter extends javax.swing.JFrame {
private JTextArea javaCodeArea;
    private JButton exportButton;
    /**
     * Creates new form JavaToXmlExporter
     */
    public JavaToXmlExporter() {
        initComponents();
                setTitle("Java to XML Exporter");
        setSize(400, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        javaCodeArea = new JTextArea();
        exportButton = new JButton("Export to XML");

        exportButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                exportToXml();
            }
        });

        JPanel panel = new JPanel();
        panel.add(new JScrollPane(javaCodeArea));
        panel.add(exportButton);

        add(panel);
    }
    private void exportToXml() {
        String javaCode = javaCodeArea.getText();

        // Convert Java code to XML (pseudo code)
        String xmlContent = convertJavaToXml(javaCode);

        // Write XML content to file
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File outputFile = fileChooser.getSelectedFile();
            try (PrintWriter writer = new PrintWriter(outputFile)) {
                writer.println(xmlContent);
                JOptionPane.showMessageDialog(this, "Java code exported to XML successfully.");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error exporting to XML: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private String convertJavaToXml(String javaCode) {
        // Implement your conversion logic here
        // This is just a placeholder method
        return "<xml>Converted XML Content</xml>";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaToXmlExporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaToXmlExporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaToXmlExporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaToXmlExporter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaToXmlExporter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}


//public class JavaToXmlExporter extends JFrame {
//    private JTextArea javaCodeArea;
//    private JButton exportButton;
//
//    public JavaToXmlExporter() {
//        setTitle("Java to XML Exporter");
//        setSize(400, 300);
//        setLocationRelativeTo(null);
//        setDefaultCloseOperation(EXIT_ON_CLOSE);
//
//        javaCodeArea = new JTextArea();
//        exportButton = new JButton("Export to XML");
//
//        exportButton.addActionListener(new ActionListener() {
//            public void actionPerformed(ActionEvent e) {
//                exportToXml();
//            }
//        });
//
//        JPanel panel = new JPanel();
//        panel.add(new JScrollPane(javaCodeArea));
//        panel.add(exportButton);
//
//        add(panel);
//    }
//
//    private void exportToXml() {
//        String javaCode = javaCodeArea.getText();
//
//        // Convert Java code to XML (pseudo code)
//        String xmlContent = convertJavaToXml(javaCode);
//
//        // Write XML content to file
//        JFileChooser fileChooser = new JFileChooser();
//        int result = fileChooser.showSaveDialog(this);
//        if (result == JFileChooser.APPROVE_OPTION) {
//            File outputFile = fileChooser.getSelectedFile();
//            try (PrintWriter writer = new PrintWriter(outputFile)) {
//                writer.println(xmlContent);
//                JOptionPane.showMessageDialog(this, "Java code exported to XML successfully.");
//            } catch (IOException ex) {
//                JOptionPane.showMessageDialog(this, "Error exporting to XML: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//            }
//        }
//    }
//
//    // Convert Java code to XML (pseudo method)
//    private String convertJavaToXml(String javaCode) {
//        // Implement your conversion logic here
//        // This is just a placeholder method
//        return "<xml>Converted XML Content</xml>";
//    }
//
//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(new Runnable() {
//            public void run() {
//                new JavaToXmlExporter().setVisible(true);
//            }
//        });
//    }
//}
