
import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.white;
import java.awt.Cursor;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fatim
 */
public class LoginForm extends javax.swing.JFrame {

    public LoginForm() {
         this.setUndecorated(true);


        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_Username = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton_Cancel = new javax.swing.JButton();
        jButton_Login1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 160, -1));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));
        jPanel1.add(jTextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 270, 32));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 270, 30));

        jButton_Cancel.setBackground(new java.awt.Color(204, 153, 0));
        jButton_Cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Cancel.setText("Cancel");
        jButton_Cancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Cancel.setFocusCycleRoot(true);
        jButton_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_CancelMouseExited(evt);
            }
        });
        jButton_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CancelActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 90, 30));

        jButton_Login1.setBackground(new java.awt.Color(204, 153, 0));
        jButton_Login1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_Login1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login1.setText("LogIn");
        jButton_Login1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Login1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Login1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_Login1MouseExited(evt);
            }
        });
        jButton_Login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Login1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 90, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student-icon-transparent-7.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 310, 460));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_CancelActionPerformed

    private void jButton_Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Login1ActionPerformed
       Connection con=MyConnection.getConnection();
       PreparedStatement ps;
        try {
            ps=con.prepareStatement("SELECT * FROM user WHERE username = ? AND password = ?");
            ps.setString(1, jTextField_Username.getText());
            ps.setString(2, String.valueOf(jPasswordField1.getPassword()));
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                MainForm mf= new MainForm();
                mf.setVisible(true);
                mf.pack();
                mf.lblusername.setText("Welcome "+jTextField_Username.getText()+" !");
                mf.lblStdCount.setText("The Total Number of Students is :"+Integer.toString(MyFunction.countData("student")));
                mf.lblCCount.setText("The Total Number of Courses is :"+Integer.toString(MyFunction.countData("course")));

                mf.setLocationRelativeTo(null);
                this.dispose();
                
            }else{
            JOptionPane.showMessageDialog(null, "Username Or Password is incorrect");            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton_Login1ActionPerformed

    private void jButton_CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseEntered
  jButton_Cancel.setBackground(Color.BLACK);
     jButton_Cancel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
     jButton_Cancel.setPreferredSize(new Dimension(1000, 100)); 
     jButton_Cancel.setForeground(white);      }//GEN-LAST:event_jButton_CancelMouseEntered

    private void jButton_CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CancelMouseExited
jButton_Cancel.setBackground(new Color(204,153,0));
          jButton_Cancel.setPreferredSize(new Dimension(1000, 100));
          jButton_Cancel.setForeground(BLACK);
    }//GEN-LAST:event_jButton_CancelMouseExited

    private void jButton_Login1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Login1MouseExited
          jButton_Login1.setBackground(new Color(204,153,0));//hhadi alkherya hia li khas tkhedmi eliha rtahiti sf 
          jButton_Login1.setPreferredSize(new Dimension(1000, 100));
          jButton_Login1.setForeground(BLACK);

    }//GEN-LAST:event_jButton_Login1MouseExited
    private void jButton_Login1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Login1MouseEntered
jButton_Login1.setBackground(Color.BLACK);
     jButton_Login1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
     jButton_Login1.setPreferredSize(new Dimension(1000, 100));
     jButton_Login1.setForeground(white); 
     
    }//GEN-LAST:event_jButton_Login1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LoginForm lf= new LoginForm();
       lf.setLocationRelativeTo(null);
        lf.setVisible(true);
          
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel;
    private javax.swing.JButton jButton_Login1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_Username;
    // End of variables declaration//GEN-END:variables
}
